components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        friends:
          type: array
          items:
            $ref: '#/components/schemas/User'
      required:
        - id
        - name